[background]
path = "/etc/greetd/greeter.jpg"
fit = "Fill"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Dracula-cursors"
font_name = "DejaVu Sans 14"
icon_theme_name = "Numix-Light"
theme_name = "Canta-dark"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
